project:
  type: website

editor: 
  mode: source
  markdown:
    wrap: 80
    canonical: true
    
execute:
  freeze: auto

description-meta: "Vikram B. Baliga"

website: 
  title: "vbaliga.github.io"
  site-url: https://vbaliga.github.io
  repo-url: https://github.com/vbaliga/vbaliga.github.io
  image: "/images/vbaliga.github.io - social preview.png"
  open-graph:
    image: "/images/vbaliga.github.io - social preview.png"
    locale: en_US
  favicon: "/images/vb32.png"
  navbar:
    pinned: true
    background: "#EE6A24"
    right:
      - text: "Home"
        href: index.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Data, software & code"
        href: data-software-code.qmd        
      - text: "Publications"
        href: publications.qmd
      - text: "Press"
        href: press.qmd
      - text: "Tidbits"
        href: blog.qmd
  search:
    location: navbar
    type: overlay
  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var site.copyright_year >}} by [{{< var author.name_no_title >}}](mailto:{{< var author.email >}}). All images by V.B.B. unless otherwise noted. <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/) license
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>

format:
  html:
    theme:
      - litera
      - html/custom.scss
    css: styles.css 
    toc: true
    highlight-style: monokai
    code-overflow: wrap
    include-in-header: 
      - file: head_tag.html
      - text: |
          <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
          <style>
            body { font-family: 'Poppins', sans-serif; }
          </style>
    include-before-body: 
      - file: ga4_tag.html
    grid:
      body-width: 900px   # pick any pixel value you like (default is 800px)
      # sidebar-width, margin-width, gutter-width keep their defaults
