---
title: "Data, software & code"
editor:
  markdown:
    wrap: 72
listing:
  id: r-packages
  contents: r-packages.yml
  type: table
  fields: [title, purpose, links, year]
  field-display-names:
    title: "Package"
    purpose: "Purpose"
    links: "Links"
    year: "Year"
  field-types:
    year: number
  field-links: [title]
  sort:
    - "year desc"
    - "title asc"
  sort-ui: [title, year]
  filter-ui: false
  table-striped: false
  table-hover: true
---

::: indent-block
Many of these were written collaboratively; see individual links for
more details.
:::

<br>

------------------------------------------------------------------------

## R packages

::: {#r-packages}
:::

------------------------------------------------------------------------

## Tutorials

::: indent-block
#### [Multi-panel plots with R](https://flightlab.github.io/MultiPanelPlotsWithR)

Developed for BIOL 548L (Visual and Oral Presentations), graduate course
at UBC. Learning objectives include:

- Determining how to import & wrangle data from diverse sources.

- Using the grammar of graphics to construct plots in `ggplot2`.

- Planning a sequence of plots that support a declarative statement of a
  result.

- Constructing multi-panel, publication-quality figures using code.
:::

------------------------------------------------------------------------

## Data & code from pubs

Some of these repositories contain phylogenies that we've inferred, but
see the [Phylogenetic trees](data-software-code.qmd#phylogenetic-trees)
section below for straightforward access to MCC & ML trees.

::: indent-block
- [figshare repository](https://doi.org/10.6084/m9.figshare.26107999)
  for: Dash S, Baliga VB, Lapsansky AB, Wylie DR, and
  Altshuler DL. 2024. Encoding of global visual motion in the avian
  pretectum shifts from a bias for temporal-to-nasal selectivity to
  omnidirectional excitation across speeds. *eNeuro*.

- [figshare repository](https://doi.org/10.6084/m9.figshare.23535717)
  for: Baliga VB, Dakin R, Wylie DR, and Altshuler DL. 2024.
  Hummingbirds use distinct control strategies for forward and hovering
  flight. *Proceedings of the Royal Society B: Biological Sciences*.

- [figshare repository](https://doi.org/10.6084/m9.figshare.19425737)
  for: Smyth G, Baliga VB, Gaede AH, Wylie DR, and Altshuler DL. 2022.
  Specializations in optic flow encodingin the pretectum of hummingbirds
  and zebra finches. *Current Biology*.

- [figshare
  repository](https://figshare.com/collections/Supplement_to_Inertia_links_avian_morphology_to_flight_manoeuvrability/5503989)
  for: Harvey, CA, Baliga VB, Wong JCM, Altshuler DL, and Inman
  DJ. 2022. Birds can transition between stable and unstable states via
  wing morphing. *Nature*. (repository arranged & maintained by
  [Christina
  Harvey](https://figshare.com/authors/Christina_Harvey/4766004))

- [figshare
  repository](https://rs.figshare.com/collections/Supplementary_material_from_Gull-inspired_joint-driven_wing_morphing_allows_adaptive_longitudinal_flight_control_/5438933)
  for: Harvey C, Baliga VB, Goates CD, Hunsaker D, and Inman DJ. 2021.
  Gull-inspired joint-driven wing morphing allows adaptive longitudinal
  flight control. *Journal of the Royal Society Interface*. (repository
  arranged & maintained by [Christina
  Harvey](https://figshare.com/authors/Christina_Harvey/4766004))

- [figshare
  repository](https://rs.figshare.com/collections/Supplementary_material_from_Phase_transformation-driven_artificial_muscle_mimics_the_multi-functionality_of_avian_wing_muscle_/5675606)
  for: Leal PBC, Cabral-Seanez M, Baliga VB, Altshuler DL, and Hartl
  DJ. 2021. Phase transformation-driven artificial muscle mimics the
  multifunctionality of avian wing muscle. *Journal of the Royal Society
  Interface*. (repository arranged & maintained by [Pedro
  Leal](https://rs.figshare.com/authors/_/11598656))

- [figshare
  repository](https://figshare.com/articles/dataset/Data_and_code_for_Flight_muscle_power_increases_with_strain_amplitude_and_decreases_with_cycle_frequency_in_zebra_finches_Taeniopygia_guttata_/12520733)
  for: Bahlman JW, Baliga VB, and Altshuler DL. 2020. Flight muscle
  power increases with strain amplitude and decreases with cycle
  frequency in zebra finches (Taeniopygia guttata). *Journal of
  Experimental Biology*.

- [figshare repository](https://doi.org/10.6084/m9.figshare.8856161)
  for: Baliga VB, Szabo I, and Altshuler DL. 2019. Range of motion in
  the avian wing is strongly associated with flight behavior and body
  mass. *Science Advances.*

- [github
  repository](https://github.com/christiandamsgaard/Evolution-of-air-breathing)
  for: Damsgaard C, Baliga VB, Bates E, Burggren W, McKenzie DJ, Taylor
  E, and Wright PA. 2019. Evolutionary and Cardio-Respiratory Physiology
  of Air-breathing and Amphibious Fishes. *Acta Physiologica.*
  (repository arranged & maintained by [Christian
  Damsgaard](https://github.com/christiandamsgaard))

- [figshare repository](https://doi.org/10.6084/m9.figshare.7658597)
  for: Baliga VB and Mehta RS. 2019. Morphology, ecology, and
  biogeography of independent origins of cleaning behavior around the
  world. *Integrative and Comparative Biology.*

- [figshare
  repository](https://doi.org/10.6084/m9.figshare.c.3977505.v1) for:
  Harvey C, Baliga VB, Lavoie P, and Altshuler DL. 2019. Wing morphing
  allows gulls to modulate static pitch stability during gliding.
  *Journal of the Royal Society Interface*. (repository arranged &
  maintained by [Christina
  Harvey](https://figshare.com/authors/Christina_Harvey/4766004))
:::

------------------------------------------------------------------------

## Phylogenetic trees

I am generally happy to share trees from posterior distributions ---
just shoot me an email.

::: indent-block
### Birds (Aves)

- 222 taxa across Aves + outgroup; from Baliga et al. 2019 (*Science
  Advances*):
  - Bayesian MCC tree
    ([download](https://vikram-baliga.squarespace.com/s/Baliga-etal-Science-Advances_222s_Avian_MCCtree.tre))
  - Maximum likelihood tree
    ([download](https://vikram-baliga.squarespace.com/s/Baliga-etal-Science-Advances_222s_Avian_MLtree.tre))

### Gobies (Gobiidae)

- 54 species of Western Atlantic gobies + outgroup; from Baliga and
  Mehta 2019 (*Integrative and Comparative Biology*):
  - Bayesian MCC tree
    ([download](https://vikram-baliga.squarespace.com/s/Gobiidae_MCC.tre))

### Marine angelfishes (Pomacanthidae)

- 72 species of marine angelfishes + outgroup; from Baliga and Mehta
  2019 (*Integrative and Comparative Biology*):
  - Bayesian MCC tree
    ([download](https://vikram-baliga.squarespace.com/s/Pomacanthidae_MCC.tre))

### Wrasses & parrotfishes (Labridae)

- 344 species of wrasses + parrotfishes + outgroup; from Baliga and Law
  2016 (*Molecular Phylogenetics and Evolution*):
  - Bayesian MCC tree
    ([download](https://vikram-baliga.squarespace.com/s/BaligaLaw2016_344SP_MCC.nwk))
  - Maximum likelihood tree
    ([download](https://vikram-baliga.squarespace.com/s/BaligaLaw2016_344SP_MLtree.nwk))
:::

------------------------------------------------------------------------
