---
title: "vbaliga.github.io"
---

Welcome to my personal site. I'm a data scientist who solves problems related to animal locomotion, evolutionary biology, and physiology. I currently am a Research Associate at the University of British Columbia ([see my department profile](https://www.zoology.ubc.ca/person/vikram-baliga)).

My research asks how musculoskeletal and visual systems allow animals to make complex movements. This often involves techniques from motion capture and virtual reality to probe animals' locomotor behaviors, along with comparative anatomy and physiology to probe the mechanisms that underlie animals' locomotor capabilities. It sometimes involves machine learning techniques to make sense of stupidly convoluted data.

This framework not only helps address how ecology shapes the evolution of animal design, but also has inspired the development of engineered structures. Some of my chief collaborators are engineers who incorporate biological insight to designing structures with multi-functional capabilities.

Truth be told, I'm not a fan of having a website dedicated to my persona. I might even delete it soon. In the meantime, please hop over to my pubs or check out my software and code to see my track record to date. If you like what you see or if you think I can help you, feel free to reach out. The point of this site is to connect with people like you.

It's also worth mentioning that there is at least one other "Vikram Baliga" with whom you may have me confused. If you are looking for a Vikram Baliga with more of a flare for horticulture, [be sure to check out his work](https://www.podchaser.com/creators/vikram-baliga-107a4YrAy8). I'm the Vikram Baliga who would [undoubtedly beat you in a James Harden look-alike contest](https://www.vikram-baliga.com/s/James-Harden.jpg) (though I can't say I'm a fan of Harden's game).

### Research profiles 

-   Google Scholar: [publications profile](https://scholar.google.com/citations?user=sXz0JqQAAAAJ&hl=en)

-   ORCID: [0000-0002-9367-8974](http://orcid.org/0000-0002-9367-8974)

-   ResearchGate: [profile](https://www.researchgate.net/profile/Vikram_Baliga)
